### ISSUE TITLE
Spaces are always added between consecutive anchor tags

### ISSUE THREAD

**Issue by nickcernis** [nickcernis/html-to-markdown#10]
This test fails:

`$this->html_gives_markdown("<a href='#'>Link 1</a><a href='#'>Link 2</a>", "[Link 1](#)[Link 2](#)");`

Output:

    Expected: [Link 1](#)[Link 2](#)
    Actual:   [Link 1](#) [Link 2](#)

Ideally, anchors that do not have spaces between them in the HTML should not see spaces between them in the resulting Markdown.

This is caused by the workaround in `convert_anchor()`, and is related to issue #9.

**Comment by colinodell** [comment]
Once #9 is fixed, this workaround will be unnecessary and can be removed, thus resolving the issue.

**Comment by colinodell** [comment]
Fixed by #28
