### ISSUE TITLE
Small improvement

### ISSUE THREAD

**Issue by lauda** [nickcernis/html-to-markdown#16]
In line 254 of current release instead of 
$markdown = preg_replace('~\s+~', ' ', $value);
i write
$markdown = preg_replace('~\s+~', ' ', preg_replace('/^\s+/', '', $value));
because most browsers ignore begin-of-line spaces

**Comment by nickcernis** [comment]
Thanks for the suggestion, but this change breaks several test cases, such as:

 `<em>Italic</em> and a <strong>bold</strong>`

`Expected : _Italic_ and a __bold__`
`Actual : _Italic_and a __bold__`
