### ISSUE TITLE
Incorrect comment?

### ISSUE THREAD

**Issue by pjt33** [nickcernis/html-to-markdown#17]
I'm puzzled by lines 273-274 in the current master:

>                 // If strip_tags is false (the default), preserve tags that don't have Markdown equivalents,
>                 // such as <span> and #text nodes on their own. C14N() canonicalizes the node to a string.

There's a

>             case "#text":

a few lines above (line 262), so isn't the comment wrong to mention #text nodes?

**Comment by nickcernis** [comment]
Corrected! Thanks for mentioning this.
