### ISSUE TITLE
Content after << is stripped in pre tags

### ISSUE THREAD

**Issue by nickcernis** [nickcernis/html-to-markdown#21]
From [this report](https://wordpress.org/support/topic/text-to-md-error?replies=2) in the Ghost WordPress plugin support forum:

`<pre>touch ~/.profile
cat >> ~/.profile <<EOF
export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
EOF
</pre>`

becomes:

`touch ~/.profile cat >> ~/.profile`

And:

`<pre>args << "--with-z=/usr/local/Cellar/zlib/1.2.8"</pre>`

becomes:

`args`

**Comment by thedannywahl** [comment]
To clarify I would expect the `<pre>` and `</pre>` tags to be preserved (in markdown format):
```language-markdown
    `touch ~/.profile 
      cat >> ~/.profile <<EOF 
      export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH" 
     EOF`
```

```language-markdown
    `args << "--with-z=/usr/local/Cellar/zlib/1.2.8"`
```

**Comment by thedannywahl** [comment]
I have not tested this in any other scenario like in `<code>`, `<p>` or unstructured 'raw' text, so I only reported this in the case I found it.  It might have no relation to a `<pre>` tag at all.

**Comment by colinodell** [comment]
These examples contain invalid HTML - those `<` and `>` characters need to be encoded as entities: http://www.w3schools.com/HTML/html_entities.asp
