### ISSUE TITLE
Don't convert anchor tags with no href

### ISSUE THREAD

**Issue by rquast** [nickcernis/html-to-markdown#22]
Links within a page are currently destroyed. Need to add an option to either remove tags with no href or include them as html in the markdown.

e.g. (up the top of the page) - 
&lt;a href="#step1"&gt;Step 1&lt;/a&gt;

(down the page)
&lt;a id="step1"&gt;&lt;/a&gt;

... fix for getting around this below ...

    private function convert_anchor($node)
    {
        .. snip ...

        if ( $href == "" ) {
            return html_entity_decode($node->C14N());
        }

        .. snip ...
    }

**Comment by nickcernis** [comment]
Links with href attributes are now preserved. Thanks for the report!

**Comment by rquast** [comment]
Thanks for the quick fix!
